version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    command: "node ."
    volumes:
      - ./src:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./config/parameters.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - ./config/parameters.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "85:80"

